In [13]:
import numpy as np

def pattern(n):
    matrix = np.zeros((n, n), dtype=int)
    row, col = n // 2, n // 2
    number = 1
    steps = 1
    
    matrix[row, col] = number

    while steps < n:
        for a in range(steps):
            col += 1
            number += 1
            matrix[row, col] = number

        for a in range(steps):
            row -= 1
            number += 1
            matrix[row, col] = number

        steps += 1

        for a in range(steps):
            col -= 1
            number += 1
            matrix[row, col] = number

        for a in range(steps):
            row += 1
            number += 1
            matrix[row, col] = number

        steps += 1

    for a in range(steps - 1):
        col += 1
        number += 1
        matrix[row, col] = number

    return matrix

def main():
    n = int(input("Enter value: "))
    pattern_matrix = pattern(n)
    print("Pattern for n =", n, ":")
    print()
    print(pattern_matrix)

if __name__ == "__main__":
    main()

Enter value:  11


Pattern for n = 11 :

[[101 100  99  98  97  96  95  94  93  92  91]
 [102  65  64  63  62  61  60  59  58  57  90]
 [103  66  37  36  35  34  33  32  31  56  89]
 [104  67  38  17  16  15  14  13  30  55  88]
 [105  68  39  18   5   4   3  12  29  54  87]
 [106  69  40  19   6   1   2  11  28  53  86]
 [107  70  41  20   7   8   9  10  27  52  85]
 [108  71  42  21  22  23  24  25  26  51  84]
 [109  72  43  44  45  46  47  48  49  50  83]
 [110  73  74  75  76  77  78  79  80  81  82]
 [111 112 113 114 115 116 117 118 119 120 121]]
